### ISSUE TITLE
NullPointerException in MapView.onSaveInstanceState

### ISSUE THREAD

**Issue by johnjohndoe** [johnjohndoe/Umweltzone#16]
Crash report from a user:

- sent: 10.10.2018
- Version: 3.3.1
- Android version: 9
- Device model: Pixel 2

# Stacktrace
``` java
Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 
    'void com.google.android.gms.maps.MapView.onSaveInstanceState(android.os.Bundle)' 
    on a null object reference 

at de.avpptr.umweltzone.map.MapFragment.onSaveInstanceState(MapFragment.java:201) 
at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:2244) 
at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1863) 
at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1931) 
at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:134) 
at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:568) 
at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511) 
at android.app.Activity.performSaveInstanceState(Activity.java:1549) 
at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1443) 
at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:4809) 
at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4139) 
at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4757) 
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4693) 
at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loop(Looper.java:193) 
at android.app.ActivityThread.main(ActivityThread.java:6669) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

# Log
``` java
0 D: Writing unhandled exception to: 
     /data/user/0/de.avpptr.umweltzone.debug/files/3.3.1-DEBUG-1538819852724.tracedroid
1 D: current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler
```

**Comment by johnjohndoe** [comment]
Another crash report via the Google Developer Console for the same issue:

- Sent at: 31.10.2018
- App version: 3.4.0
- Device model: Philips Xenium S386 (S386)
- Android version: 7.0
