### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.x.a()' on a null object reference

### ISSUE THREAD

**Issue by johnjohndoe** [johnjohndoe/Umweltzone#6]
Given the following [development branch](https://github.com/johnjohndoe/Umweltzone/tree/dev-compile-sdk-23) where:
- `minSdkVersion 9` is used
- `play-services-* 8.4.0` is used
- `compileSdkVersion 23` and `com.android.support:design:23.4.0` are used

# Crash

- When a **release** build with Proguard is compiled then the app **crashes** on **first** start up with the following stacktrace:

``` java
E  java.lang.RuntimeException: Unable to start activity 
   ComponentInfo{de.avpptr.umweltzone/de.avpptr.umweltzone.map.MainActivity}: an
   droid.view.InflateException: Binary XML file line #76: Binary XML file line #33: 
   Error inflating class Button

E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
E      at android.app.ActivityThread.-wrap11(ActivityThread.java)
E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
E      at android.os.Handler.dispatchMessage(Handler.java:102)
E      at android.os.Looper.loop(Looper.java:148)
E      at android.app.ActivityThread.main(ActivityThread.java:5417)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

E  Caused by: android.view.InflateException: Binary XML file line #76: 
   Binary XML file line #33: Error inflating class Button
E      at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
E      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
E      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
E      at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
E      at com.android.internal.app.AlertController.installContent(AlertController.java:233)
E      at android.app.AlertDialog.onCreate(AlertDialog.java:423)
E      at android.app.Dialog.dispatchOnCreate(Dialog.java:394)
E      at android.app.Dialog.show(Dialog.java:295)
E      at de.avpptr.umweltzone.map.MainActivity.onCreate(Unknown Source)
E      at android.app.Activity.performCreate(Activity.java:6237)
E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
E      ... 9 more

E  Caused by: android.view.InflateException: Binary XML file line #33: 
    Error inflating class Button
E      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
E      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
E      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
E      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
E      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
E      at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
E      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
E      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
E      ... 20 more

E  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 
   'void android.support.v7.widget.x.a()' on a null object reference
E      at android.support.v7.widget.AppCompatButton.setBackgroundDrawable(Unknown Source)
E      at android.view.View.setBackground(View.java:17221)
E      at android.view.View.<init>(View.java:4328)
E      at android.widget.TextView.<init>(TextView.java:677)
E      at android.widget.Button.<init>(Button.java:109)
E      at android.widget.Button.<init>(Button.java:105)
E      at android.support.v7.widget.AppCompatButton.<init>(Unknown Source)
E      at android.support.v7.widget.AppCompatButton.<init>(Unknown Source)
E      at android.support.v7.app.u.a(Unknown Source)
E      at android.support.v7.app.AppCompatDelegateImplV7.a(Unknown Source)
E      at android.support.v4.view.z.onCreateView(Unknown Source)
E      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
E      ... 27 more
```

# Findings

- `play-services` dependency tree:
> com.google.android.gms:play-services-base:8.4.0
> -> com.google.android.gms:play-services-basement:8.4.0
>   -> com.android.support:support-v4:23.0.0

- The app starts successfully when Proguard is **omitted**.
- The app starts successfully when the [ckChangeLog dialog is **not** invoked in `MainActivity.onCreate`](https://github.com/johnjohndoe/Umweltzone/blob/dev-compile-sdk-23/Umweltzone/src/main/java/de/avpptr/umweltzone/map/MainActivity.java#L46).

---

@cketti Can you see why the crash happens?

**Comment by johnjohndoe** [comment]
Resolved in 019c3d681968d49fc4322e053a5ae66de0e76d44. Thank you @cketti :hugs:
